name: CD Firebase
on:
  push:
    branches:
      - main
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: GitHubActionsResultNotificationBot
  SLACK_CHANNEL: next-web-technology-net
jobs:
  cd-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci --force
      - run: npm run build --if-present
      - run: npm ci
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions
      - run: npx firebase deploy --project=default --token=${{ secrets.FIREBASE_TOKEN }}
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
