name: CI Firebase Functions
on: [pull_request]
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: GitHubActionsResultNotificationBot
  SLACK_CHANNEL: next-web-technology-net
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: ./functions
      - run: npm run build --if-present
        working-directory: ./functions
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: CI Success
          SLACK_COLOR: good
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: CI Failure
          SLACK_COLOR: danger
